[2024-09-12T13:40:16.232+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T13:18:16.126550+00:00 [queued]>
[2024-09-12T13:40:16.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T13:18:16.126550+00:00 [queued]>
[2024-09-12T13:40:16.256+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-09-12T13:40:16.296+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): crawl_list_restaurant> on 2024-09-12 13:18:16.126550+00:00
[2024-09-12T13:40:16.308+0000] {standard_task_runner.py:60} INFO - Started process 11757 to run task
[2024-09-12T13:40:16.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'shopeefood_crawl_and_report', 'crawl_list_restaurant', 'manual__2024-09-12T13:18:16.126550+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp8nafpxnn']
[2024-09-12T13:40:16.321+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask crawl_list_restaurant
[2024-09-12T13:40:16.449+0000] {task_command.py:423} INFO - Running <TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T13:18:16.126550+00:00 [running]> on host bc7cb9c82b76
[2024-09-12T13:40:16.935+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shopeefood_crawl_and_report' AIRFLOW_CTX_TASK_ID='crawl_list_restaurant' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T13:18:16.126550+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T13:18:16.126550+00:00'
[2024-09-12T13:43:52.537+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-12T13:43:52.540+0000] {process_utils.py:131} INFO - Sending 15 to group 11757. PIDs of all processes in the group: [11757]
[2024-09-12T13:43:52.541+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 11757
[2024-09-12T13:43:52.543+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-12T13:43:52.595+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=11757, status='terminated', exitcode=0, started='13:40:15') (11757) terminated with exit code 0
